name: Docker

on:
  workflow_call: 

jobs:

  docker:
    runs-on: ubuntu:latest
        
    steps:
    - name: repo checkout
    - uses: actions/checkout@v3

    - name: set up docker build
      uses: docker/setup-buildx-action@v3.6.1

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: efranca
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
          
